### PR TITLE
Adding option to choose delimiter styles

### PR DESCRIPTION
**Pull request by NicolasBoumal**
Hello Sophie, Bento,

Thanks a lot for this extension, it's been very helpful!

My collaborators and I find it more natural to use the traditional latex convention for dollar-sign delimiters in slack ($...$ for inline, $$...$$ for display).

This pull request adds an option to the chrome extension so users can easily switch from one style to the other if they so choose.

The default option value coincides with your style choice.

I hope you see the use for it. Let me know if you'd like to update the official extension on the chrome web store. Otherwise, I can upload it there as a separate extension and indicate clearly that this is just a small modification of your work.

Best wishes,
Nicolas

### CODE REVIEW

**Comment by NicolasBoumal** [comment]
One small thing I forgot: I had to rename your file 600*480.png into 600x480.png because the asterisk is a forbidden character for Windows file names.

**Comment by sophiehuiberts** [comment]
Hey Nicolas, thank you so much for doing this! Its a feature that more people have requested. I'll review the code, and then incorporate your code in the new version of the extension. I hope to put the new version on the addon stores some time this week, together with some other things of my own that are in the works.

I plan to add tripple dollars $$$.$$$ to be rendered in display mode even in the new LaTeX-compatible mode, just in case people have multiple Slack workspaces and can't coordinate a setting with all of their collaborators.

One question for you: Do you agree to license your contribution under the MIT license?

**Comment by NicolasBoumal** [comment]
Hello Sophie,

Great to read that you'd be happy to include this in the main code base (provided it withstands your code review of course).

About handling triple dollar signs even with the new option: I was thinking of doing the same actually. I think it's a good way to proceed.

The MIT license for my modifications is perfect.

Looking forward to the update on the web store, and let me know if I can be of help.

**Comment by sophiehuiberts** [comment]
The new version was just published. :) Thanks again for your contribution!

**Comment by NicolasBoumal** [comment]
This is great, thank you!

**Pull request merged**
